---
- name: Install clamav
  apt:
    name:
      - clamav
      - clamav-daemon
  register: apt_install

- name: Create freshclam configurations
  template:
    src: freshclam.conf.j2
    dest: /etc/clamav/freshclam.conf
    owner: root
    group: clamav
    mode: 0640
  notify: Restart clamav

- name: Download initial clam databases
  command:
    cmd: freshclam
    creates: /var/lib/clamav/main.cvd
  when: apt_install.changed

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - clamav-daemon
    - clamav-freshclam
