---
- name: Install clamav
  apt:
    name:
      - clamav
      - clamav-daemon

- name: Create freshclam configurations
  template:
    src: freshclam.conf.j2
    dest: /etc/clamav/freshclam.conf
    owner: root
    group: clamav
    mode: 0640
  notify: Restart clamav

- name: Create tmpfiles configuration
  template:
    src: tmpfiles.conf.j2
    dest: /etc/tmpfiles.d/clamav.conf
    owner: root
    group: root
    mode: 0644
  register: tmpfiles

- name: Create systemd tmpfiles
  command: systemd-tmpfiles --create
  when: tmpfiles.changed

- name: Download initial clam databases
  command:
    cmd: freshclam
    creates: /var/lib/clamav/main.cvd

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - clamav-daemon
    - clamav-freshclam
